# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/danilo-alencar/Documents/GitHub/UHF_LoRa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/danilo-alencar/Documents/GitHub/UHF_LoRa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo-alencar/Documents/GitHub/UHF_LoRa/CMakeFiles /home/danilo-alencar/Documents/GitHub/UHF_LoRa//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/danilo-alencar/Documents/GitHub/UHF_LoRa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RS41HUP.elf

# Build rule for target.
RS41HUP.elf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 RS41HUP.elf
.PHONY : RS41HUP.elf

# fast build rule for target.
RS41HUP.elf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/build
.PHONY : RS41HUP.elf/fast

#=============================================================================
# Target rules for targets named program

# Build rule for target.
program: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 program
.PHONY : program

# fast build rule for target.
program/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/program.dir/build.make CMakeFiles/program.dir/build
.PHONY : program/fast

QAPRSBase.obj: QAPRSBase.cpp.obj
.PHONY : QAPRSBase.obj

# target to build an object file
QAPRSBase.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/QAPRSBase.cpp.obj
.PHONY : QAPRSBase.cpp.obj

QAPRSBase.i: QAPRSBase.cpp.i
.PHONY : QAPRSBase.i

# target to preprocess a source file
QAPRSBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/QAPRSBase.cpp.i
.PHONY : QAPRSBase.cpp.i

QAPRSBase.s: QAPRSBase.cpp.s
.PHONY : QAPRSBase.s

# target to generate assembly for a file
QAPRSBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/QAPRSBase.cpp.s
.PHONY : QAPRSBase.cpp.s

aprs.obj: aprs.cpp.obj
.PHONY : aprs.obj

# target to build an object file
aprs.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/aprs.cpp.obj
.PHONY : aprs.cpp.obj

aprs.i: aprs.cpp.i
.PHONY : aprs.i

# target to preprocess a source file
aprs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/aprs.cpp.i
.PHONY : aprs.cpp.i

aprs.s: aprs.cpp.s
.PHONY : aprs.s

# target to generate assembly for a file
aprs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/aprs.cpp.s
.PHONY : aprs.cpp.s

cmsis_boot/startup/startup_stm32f10x_md_vl.obj: cmsis_boot/startup/startup_stm32f10x_md_vl.c.obj
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.obj

# target to build an object file
cmsis_boot/startup/startup_stm32f10x_md_vl.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/startup/startup_stm32f10x_md_vl.c.obj
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.c.obj

cmsis_boot/startup/startup_stm32f10x_md_vl.i: cmsis_boot/startup/startup_stm32f10x_md_vl.c.i
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.i

# target to preprocess a source file
cmsis_boot/startup/startup_stm32f10x_md_vl.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/startup/startup_stm32f10x_md_vl.c.i
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.c.i

cmsis_boot/startup/startup_stm32f10x_md_vl.s: cmsis_boot/startup/startup_stm32f10x_md_vl.c.s
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.s

# target to generate assembly for a file
cmsis_boot/startup/startup_stm32f10x_md_vl.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/startup/startup_stm32f10x_md_vl.c.s
.PHONY : cmsis_boot/startup/startup_stm32f10x_md_vl.c.s

cmsis_boot/system_stm32f10x.obj: cmsis_boot/system_stm32f10x.c.obj
.PHONY : cmsis_boot/system_stm32f10x.obj

# target to build an object file
cmsis_boot/system_stm32f10x.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/system_stm32f10x.c.obj
.PHONY : cmsis_boot/system_stm32f10x.c.obj

cmsis_boot/system_stm32f10x.i: cmsis_boot/system_stm32f10x.c.i
.PHONY : cmsis_boot/system_stm32f10x.i

# target to preprocess a source file
cmsis_boot/system_stm32f10x.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/system_stm32f10x.c.i
.PHONY : cmsis_boot/system_stm32f10x.c.i

cmsis_boot/system_stm32f10x.s: cmsis_boot/system_stm32f10x.c.s
.PHONY : cmsis_boot/system_stm32f10x.s

# target to generate assembly for a file
cmsis_boot/system_stm32f10x.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/cmsis_boot/system_stm32f10x.c.s
.PHONY : cmsis_boot/system_stm32f10x.c.s

delay.obj: delay.c.obj
.PHONY : delay.obj

# target to build an object file
delay.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/delay.c.obj
.PHONY : delay.c.obj

delay.i: delay.c.i
.PHONY : delay.i

# target to preprocess a source file
delay.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/delay.c.i
.PHONY : delay.c.i

delay.s: delay.c.s
.PHONY : delay.s

# target to generate assembly for a file
delay.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/delay.c.s
.PHONY : delay.c.s

f_rtty.obj: f_rtty.c.obj
.PHONY : f_rtty.obj

# target to build an object file
f_rtty.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/f_rtty.c.obj
.PHONY : f_rtty.c.obj

f_rtty.i: f_rtty.c.i
.PHONY : f_rtty.i

# target to preprocess a source file
f_rtty.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/f_rtty.c.i
.PHONY : f_rtty.c.i

f_rtty.s: f_rtty.c.s
.PHONY : f_rtty.s

# target to generate assembly for a file
f_rtty.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/f_rtty.c.s
.PHONY : f_rtty.c.s

horus_l2.obj: horus_l2.c.obj
.PHONY : horus_l2.obj

# target to build an object file
horus_l2.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/horus_l2.c.obj
.PHONY : horus_l2.c.obj

horus_l2.i: horus_l2.c.i
.PHONY : horus_l2.i

# target to preprocess a source file
horus_l2.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/horus_l2.c.i
.PHONY : horus_l2.c.i

horus_l2.s: horus_l2.c.s
.PHONY : horus_l2.s

# target to generate assembly for a file
horus_l2.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/horus_l2.c.s
.PHONY : horus_l2.c.s

init.obj: init.c.obj
.PHONY : init.obj

# target to build an object file
init.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/init.c.obj
.PHONY : init.c.obj

init.i: init.c.i
.PHONY : init.i

# target to preprocess a source file
init.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/init.c.i
.PHONY : init.c.i

init.s: init.c.s
.PHONY : init.s

# target to generate assembly for a file
init.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/init.c.s
.PHONY : init.c.s

locator.obj: locator.c.obj
.PHONY : locator.obj

# target to build an object file
locator.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/locator.c.obj
.PHONY : locator.c.obj

locator.i: locator.c.i
.PHONY : locator.i

# target to preprocess a source file
locator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/locator.c.i
.PHONY : locator.c.i

locator.s: locator.c.s
.PHONY : locator.s

# target to generate assembly for a file
locator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/locator.c.s
.PHONY : locator.c.s

main.obj: main.c.obj
.PHONY : main.obj

# target to build an object file
main.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/main.c.obj
.PHONY : main.c.obj

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/main.c.s
.PHONY : main.c.s

mfsk.obj: mfsk.c.obj
.PHONY : mfsk.obj

# target to build an object file
mfsk.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/mfsk.c.obj
.PHONY : mfsk.c.obj

mfsk.i: mfsk.c.i
.PHONY : mfsk.i

# target to preprocess a source file
mfsk.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/mfsk.c.i
.PHONY : mfsk.c.i

mfsk.s: mfsk.c.s
.PHONY : mfsk.s

# target to generate assembly for a file
mfsk.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/mfsk.c.s
.PHONY : mfsk.c.s

morse.obj: morse.c.obj
.PHONY : morse.obj

# target to build an object file
morse.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/morse.c.obj
.PHONY : morse.c.obj

morse.i: morse.c.i
.PHONY : morse.i

# target to preprocess a source file
morse.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/morse.c.i
.PHONY : morse.c.i

morse.s: morse.c.s
.PHONY : morse.s

# target to generate assembly for a file
morse.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/morse.c.s
.PHONY : morse.c.s

radio.obj: radio.c.obj
.PHONY : radio.obj

# target to build an object file
radio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/radio.c.obj
.PHONY : radio.c.obj

radio.i: radio.c.i
.PHONY : radio.i

# target to preprocess a source file
radio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/radio.c.i
.PHONY : radio.c.i

radio.s: radio.c.s
.PHONY : radio.s

# target to generate assembly for a file
radio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/radio.c.s
.PHONY : radio.c.s

stm_lib/src/misc.obj: stm_lib/src/misc.c.obj
.PHONY : stm_lib/src/misc.obj

# target to build an object file
stm_lib/src/misc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/misc.c.obj
.PHONY : stm_lib/src/misc.c.obj

stm_lib/src/misc.i: stm_lib/src/misc.c.i
.PHONY : stm_lib/src/misc.i

# target to preprocess a source file
stm_lib/src/misc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/misc.c.i
.PHONY : stm_lib/src/misc.c.i

stm_lib/src/misc.s: stm_lib/src/misc.c.s
.PHONY : stm_lib/src/misc.s

# target to generate assembly for a file
stm_lib/src/misc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/misc.c.s
.PHONY : stm_lib/src/misc.c.s

stm_lib/src/stm32f10x_adc.obj: stm_lib/src/stm32f10x_adc.c.obj
.PHONY : stm_lib/src/stm32f10x_adc.obj

# target to build an object file
stm_lib/src/stm32f10x_adc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_adc.c.obj
.PHONY : stm_lib/src/stm32f10x_adc.c.obj

stm_lib/src/stm32f10x_adc.i: stm_lib/src/stm32f10x_adc.c.i
.PHONY : stm_lib/src/stm32f10x_adc.i

# target to preprocess a source file
stm_lib/src/stm32f10x_adc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_adc.c.i
.PHONY : stm_lib/src/stm32f10x_adc.c.i

stm_lib/src/stm32f10x_adc.s: stm_lib/src/stm32f10x_adc.c.s
.PHONY : stm_lib/src/stm32f10x_adc.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_adc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_adc.c.s
.PHONY : stm_lib/src/stm32f10x_adc.c.s

stm_lib/src/stm32f10x_dma.obj: stm_lib/src/stm32f10x_dma.c.obj
.PHONY : stm_lib/src/stm32f10x_dma.obj

# target to build an object file
stm_lib/src/stm32f10x_dma.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_dma.c.obj
.PHONY : stm_lib/src/stm32f10x_dma.c.obj

stm_lib/src/stm32f10x_dma.i: stm_lib/src/stm32f10x_dma.c.i
.PHONY : stm_lib/src/stm32f10x_dma.i

# target to preprocess a source file
stm_lib/src/stm32f10x_dma.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_dma.c.i
.PHONY : stm_lib/src/stm32f10x_dma.c.i

stm_lib/src/stm32f10x_dma.s: stm_lib/src/stm32f10x_dma.c.s
.PHONY : stm_lib/src/stm32f10x_dma.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_dma.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_dma.c.s
.PHONY : stm_lib/src/stm32f10x_dma.c.s

stm_lib/src/stm32f10x_flash.obj: stm_lib/src/stm32f10x_flash.c.obj
.PHONY : stm_lib/src/stm32f10x_flash.obj

# target to build an object file
stm_lib/src/stm32f10x_flash.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_flash.c.obj
.PHONY : stm_lib/src/stm32f10x_flash.c.obj

stm_lib/src/stm32f10x_flash.i: stm_lib/src/stm32f10x_flash.c.i
.PHONY : stm_lib/src/stm32f10x_flash.i

# target to preprocess a source file
stm_lib/src/stm32f10x_flash.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_flash.c.i
.PHONY : stm_lib/src/stm32f10x_flash.c.i

stm_lib/src/stm32f10x_flash.s: stm_lib/src/stm32f10x_flash.c.s
.PHONY : stm_lib/src/stm32f10x_flash.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_flash.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_flash.c.s
.PHONY : stm_lib/src/stm32f10x_flash.c.s

stm_lib/src/stm32f10x_gpio.obj: stm_lib/src/stm32f10x_gpio.c.obj
.PHONY : stm_lib/src/stm32f10x_gpio.obj

# target to build an object file
stm_lib/src/stm32f10x_gpio.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_gpio.c.obj
.PHONY : stm_lib/src/stm32f10x_gpio.c.obj

stm_lib/src/stm32f10x_gpio.i: stm_lib/src/stm32f10x_gpio.c.i
.PHONY : stm_lib/src/stm32f10x_gpio.i

# target to preprocess a source file
stm_lib/src/stm32f10x_gpio.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_gpio.c.i
.PHONY : stm_lib/src/stm32f10x_gpio.c.i

stm_lib/src/stm32f10x_gpio.s: stm_lib/src/stm32f10x_gpio.c.s
.PHONY : stm_lib/src/stm32f10x_gpio.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_gpio.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_gpio.c.s
.PHONY : stm_lib/src/stm32f10x_gpio.c.s

stm_lib/src/stm32f10x_pwr.obj: stm_lib/src/stm32f10x_pwr.c.obj
.PHONY : stm_lib/src/stm32f10x_pwr.obj

# target to build an object file
stm_lib/src/stm32f10x_pwr.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_pwr.c.obj
.PHONY : stm_lib/src/stm32f10x_pwr.c.obj

stm_lib/src/stm32f10x_pwr.i: stm_lib/src/stm32f10x_pwr.c.i
.PHONY : stm_lib/src/stm32f10x_pwr.i

# target to preprocess a source file
stm_lib/src/stm32f10x_pwr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_pwr.c.i
.PHONY : stm_lib/src/stm32f10x_pwr.c.i

stm_lib/src/stm32f10x_pwr.s: stm_lib/src/stm32f10x_pwr.c.s
.PHONY : stm_lib/src/stm32f10x_pwr.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_pwr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_pwr.c.s
.PHONY : stm_lib/src/stm32f10x_pwr.c.s

stm_lib/src/stm32f10x_rcc.obj: stm_lib/src/stm32f10x_rcc.c.obj
.PHONY : stm_lib/src/stm32f10x_rcc.obj

# target to build an object file
stm_lib/src/stm32f10x_rcc.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_rcc.c.obj
.PHONY : stm_lib/src/stm32f10x_rcc.c.obj

stm_lib/src/stm32f10x_rcc.i: stm_lib/src/stm32f10x_rcc.c.i
.PHONY : stm_lib/src/stm32f10x_rcc.i

# target to preprocess a source file
stm_lib/src/stm32f10x_rcc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_rcc.c.i
.PHONY : stm_lib/src/stm32f10x_rcc.c.i

stm_lib/src/stm32f10x_rcc.s: stm_lib/src/stm32f10x_rcc.c.s
.PHONY : stm_lib/src/stm32f10x_rcc.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_rcc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_rcc.c.s
.PHONY : stm_lib/src/stm32f10x_rcc.c.s

stm_lib/src/stm32f10x_spi.obj: stm_lib/src/stm32f10x_spi.c.obj
.PHONY : stm_lib/src/stm32f10x_spi.obj

# target to build an object file
stm_lib/src/stm32f10x_spi.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_spi.c.obj
.PHONY : stm_lib/src/stm32f10x_spi.c.obj

stm_lib/src/stm32f10x_spi.i: stm_lib/src/stm32f10x_spi.c.i
.PHONY : stm_lib/src/stm32f10x_spi.i

# target to preprocess a source file
stm_lib/src/stm32f10x_spi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_spi.c.i
.PHONY : stm_lib/src/stm32f10x_spi.c.i

stm_lib/src/stm32f10x_spi.s: stm_lib/src/stm32f10x_spi.c.s
.PHONY : stm_lib/src/stm32f10x_spi.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_spi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_spi.c.s
.PHONY : stm_lib/src/stm32f10x_spi.c.s

stm_lib/src/stm32f10x_tim.obj: stm_lib/src/stm32f10x_tim.c.obj
.PHONY : stm_lib/src/stm32f10x_tim.obj

# target to build an object file
stm_lib/src/stm32f10x_tim.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_tim.c.obj
.PHONY : stm_lib/src/stm32f10x_tim.c.obj

stm_lib/src/stm32f10x_tim.i: stm_lib/src/stm32f10x_tim.c.i
.PHONY : stm_lib/src/stm32f10x_tim.i

# target to preprocess a source file
stm_lib/src/stm32f10x_tim.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_tim.c.i
.PHONY : stm_lib/src/stm32f10x_tim.c.i

stm_lib/src/stm32f10x_tim.s: stm_lib/src/stm32f10x_tim.c.s
.PHONY : stm_lib/src/stm32f10x_tim.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_tim.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_tim.c.s
.PHONY : stm_lib/src/stm32f10x_tim.c.s

stm_lib/src/stm32f10x_usart.obj: stm_lib/src/stm32f10x_usart.c.obj
.PHONY : stm_lib/src/stm32f10x_usart.obj

# target to build an object file
stm_lib/src/stm32f10x_usart.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_usart.c.obj
.PHONY : stm_lib/src/stm32f10x_usart.c.obj

stm_lib/src/stm32f10x_usart.i: stm_lib/src/stm32f10x_usart.c.i
.PHONY : stm_lib/src/stm32f10x_usart.i

# target to preprocess a source file
stm_lib/src/stm32f10x_usart.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_usart.c.i
.PHONY : stm_lib/src/stm32f10x_usart.c.i

stm_lib/src/stm32f10x_usart.s: stm_lib/src/stm32f10x_usart.c.s
.PHONY : stm_lib/src/stm32f10x_usart.s

# target to generate assembly for a file
stm_lib/src/stm32f10x_usart.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/stm_lib/src/stm32f10x_usart.c.s
.PHONY : stm_lib/src/stm32f10x_usart.c.s

syscalls/syscalls.obj: syscalls/syscalls.c.obj
.PHONY : syscalls/syscalls.obj

# target to build an object file
syscalls/syscalls.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/syscalls/syscalls.c.obj
.PHONY : syscalls/syscalls.c.obj

syscalls/syscalls.i: syscalls/syscalls.c.i
.PHONY : syscalls/syscalls.i

# target to preprocess a source file
syscalls/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/syscalls/syscalls.c.i
.PHONY : syscalls/syscalls.c.i

syscalls/syscalls.s: syscalls/syscalls.c.s
.PHONY : syscalls/syscalls.s

# target to generate assembly for a file
syscalls/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/syscalls/syscalls.c.s
.PHONY : syscalls/syscalls.c.s

ublox.obj: ublox.c.obj
.PHONY : ublox.obj

# target to build an object file
ublox.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/ublox.c.obj
.PHONY : ublox.c.obj

ublox.i: ublox.c.i
.PHONY : ublox.i

# target to preprocess a source file
ublox.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/ublox.c.i
.PHONY : ublox.c.i

ublox.s: ublox.c.s
.PHONY : ublox.s

# target to generate assembly for a file
ublox.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/ublox.c.s
.PHONY : ublox.c.s

util.obj: util.c.obj
.PHONY : util.obj

# target to build an object file
util.c.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/util.c.obj
.PHONY : util.c.obj

util.i: util.c.i
.PHONY : util.i

# target to preprocess a source file
util.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/util.c.i
.PHONY : util.c.i

util.s: util.c.s
.PHONY : util.s

# target to generate assembly for a file
util.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/RS41HUP.elf.dir/build.make CMakeFiles/RS41HUP.elf.dir/util.c.s
.PHONY : util.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... program"
	@echo "... RS41HUP.elf"
	@echo "... QAPRSBase.obj"
	@echo "... QAPRSBase.i"
	@echo "... QAPRSBase.s"
	@echo "... aprs.obj"
	@echo "... aprs.i"
	@echo "... aprs.s"
	@echo "... cmsis_boot/startup/startup_stm32f10x_md_vl.obj"
	@echo "... cmsis_boot/startup/startup_stm32f10x_md_vl.i"
	@echo "... cmsis_boot/startup/startup_stm32f10x_md_vl.s"
	@echo "... cmsis_boot/system_stm32f10x.obj"
	@echo "... cmsis_boot/system_stm32f10x.i"
	@echo "... cmsis_boot/system_stm32f10x.s"
	@echo "... delay.obj"
	@echo "... delay.i"
	@echo "... delay.s"
	@echo "... f_rtty.obj"
	@echo "... f_rtty.i"
	@echo "... f_rtty.s"
	@echo "... horus_l2.obj"
	@echo "... horus_l2.i"
	@echo "... horus_l2.s"
	@echo "... init.obj"
	@echo "... init.i"
	@echo "... init.s"
	@echo "... locator.obj"
	@echo "... locator.i"
	@echo "... locator.s"
	@echo "... main.obj"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mfsk.obj"
	@echo "... mfsk.i"
	@echo "... mfsk.s"
	@echo "... morse.obj"
	@echo "... morse.i"
	@echo "... morse.s"
	@echo "... radio.obj"
	@echo "... radio.i"
	@echo "... radio.s"
	@echo "... stm_lib/src/misc.obj"
	@echo "... stm_lib/src/misc.i"
	@echo "... stm_lib/src/misc.s"
	@echo "... stm_lib/src/stm32f10x_adc.obj"
	@echo "... stm_lib/src/stm32f10x_adc.i"
	@echo "... stm_lib/src/stm32f10x_adc.s"
	@echo "... stm_lib/src/stm32f10x_dma.obj"
	@echo "... stm_lib/src/stm32f10x_dma.i"
	@echo "... stm_lib/src/stm32f10x_dma.s"
	@echo "... stm_lib/src/stm32f10x_flash.obj"
	@echo "... stm_lib/src/stm32f10x_flash.i"
	@echo "... stm_lib/src/stm32f10x_flash.s"
	@echo "... stm_lib/src/stm32f10x_gpio.obj"
	@echo "... stm_lib/src/stm32f10x_gpio.i"
	@echo "... stm_lib/src/stm32f10x_gpio.s"
	@echo "... stm_lib/src/stm32f10x_pwr.obj"
	@echo "... stm_lib/src/stm32f10x_pwr.i"
	@echo "... stm_lib/src/stm32f10x_pwr.s"
	@echo "... stm_lib/src/stm32f10x_rcc.obj"
	@echo "... stm_lib/src/stm32f10x_rcc.i"
	@echo "... stm_lib/src/stm32f10x_rcc.s"
	@echo "... stm_lib/src/stm32f10x_spi.obj"
	@echo "... stm_lib/src/stm32f10x_spi.i"
	@echo "... stm_lib/src/stm32f10x_spi.s"
	@echo "... stm_lib/src/stm32f10x_tim.obj"
	@echo "... stm_lib/src/stm32f10x_tim.i"
	@echo "... stm_lib/src/stm32f10x_tim.s"
	@echo "... stm_lib/src/stm32f10x_usart.obj"
	@echo "... stm_lib/src/stm32f10x_usart.i"
	@echo "... stm_lib/src/stm32f10x_usart.s"
	@echo "... syscalls/syscalls.obj"
	@echo "... syscalls/syscalls.i"
	@echo "... syscalls/syscalls.s"
	@echo "... ublox.obj"
	@echo "... ublox.i"
	@echo "... ublox.s"
	@echo "... util.obj"
	@echo "... util.i"
	@echo "... util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

